{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibfitbit/1.0.0/klibfitbit-1.0.0.module",
    "group": "org.jraf.klibfitbit",
    "module": "klibfitbit",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.0.jar",
          "url": "klibfitbit-jvm-1.0.0.jar",
          "size": 66424,
          "sha512": "6b7cd506075c5aa6f63f780b96546986baaf21e7ace08b9a864ac2f83ebd22f4cbe2eb48626917e76ad9faad3be7749791f026d3e06fb518f31d078608d759fb",
          "sha256": "b03a09c27e329576daff66f7d8fbe85d64d9fbe3b76653a6d2ff87572b0f9e6b",
          "sha1": "269cd1b0c1c41fceb80f5a21f319e23aac8e6a97",
          "md5": "5a763ac4dd1ded036c626bef2708464a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.0.jar",
          "url": "klibfitbit-jvm-1.0.0.jar",
          "size": 66424,
          "sha512": "6b7cd506075c5aa6f63f780b96546986baaf21e7ace08b9a864ac2f83ebd22f4cbe2eb48626917e76ad9faad3be7749791f026d3e06fb518f31d078608d759fb",
          "sha256": "b03a09c27e329576daff66f7d8fbe85d64d9fbe3b76653a6d2ff87572b0f9e6b",
          "sha1": "269cd1b0c1c41fceb80f5a21f319e23aac8e6a97",
          "md5": "5a763ac4dd1ded036c626bef2708464a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.0-sources.jar",
          "url": "klibfitbit-jvm-1.0.0-sources.jar",
          "size": 15806,
          "sha512": "0c98db64b598e9044ae8166ce4ef0429a09da9becbc9c8689a076fee1795c62f71b55f594795552108726230100cbfe1c77ce429141d16a2a0c2d5aa0e359c49",
          "sha256": "dd2b4158bd78ca20f139b0780d99a12b200e49ca763369ce6e1e35fff15cf263",
          "sha1": "e9b7c169785c9aedec525dab0d4482bc73b5a653",
          "md5": "e50fb703c3b52f77c0da58fca9eaebda"
        }
      ]
    }
  ]
}
