pom.groupId=org.jraf.klibghealth
pom.version=1.1.1-SNAPSHOT
pom.description=A Google Health (previously Fitbit) API client library for Kotlin
pom.vcsUrl=https://github.com/BoD/klibghealth
pom.developer=Benoit \'BoD\' Lubek
pom.license=Apache-2.0
java.compatibility=17
kotlin.compatibility=2.2.0
kdoc.projects=:klibghealth
