{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibfitbit",
    "module": "klibfitbit",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-metadata-1.0.3-SNAPSHOT.jar",
          "url": "klibfitbit-1.0.3-SNAPSHOT.jar",
          "size": 13883,
          "sha512": "827631335602fbe823c94b7a7f1d5934e04ecb3ef667b4aab03d4f034046c6a1b6098da0361a0a5a03823f2364b0524895f9fe3ddb50228ffac64e133f6fc067",
          "sha256": "706b4a8f6ff5a67134080cc455f9cbd4837df26937e93b197bc40f9fd3a5781d",
          "sha1": "e251bb1eb52fdeb0e04aeb78e00cd681b718f77f",
          "md5": "425e4d813cb2cbfb53c6885dec4d8fea"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibfitbit-kotlin-1.0.3-SNAPSHOT-sources.jar",
          "url": "klibfitbit-1.0.3-SNAPSHOT-sources.jar",
          "size": 17134,
          "sha512": "f772fa5595c9759c7e70363e5d851e1bce1ae8f84434bf24ed4e4a4c19b4151e717bc06f8d461fba72eab79eb9d9b4d328b3b0b489db35c9bc1c052431b2ce29",
          "sha256": "afe9e3dd5e694774d51cfc870ce3af69123098a7a34d16b10afc8206de0267a9",
          "sha1": "3af482ea89a034cd5cc1fa000cdda3d162eb2c6d",
          "md5": "bb7a32d68561b9d74a66f06517df25d6"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibfitbit-jvm/1.0.3-SNAPSHOT/klibfitbit-jvm-1.0.3-SNAPSHOT.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-jvm",
        "version": "1.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibfitbit-jvm/1.0.3-SNAPSHOT/klibfitbit-jvm-1.0.3-SNAPSHOT.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-jvm",
        "version": "1.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibfitbit-jvm/1.0.3-SNAPSHOT/klibfitbit-jvm-1.0.3-SNAPSHOT.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-jvm",
        "version": "1.0.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibfitbit-macosarm64/1.0.3-SNAPSHOT/klibfitbit-macosarm64-1.0.3-SNAPSHOT.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-macosarm64",
        "version": "1.0.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibfitbit-macosarm64/1.0.3-SNAPSHOT/klibfitbit-macosarm64-1.0.3-SNAPSHOT.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-macosarm64",
        "version": "1.0.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibfitbit-macosarm64/1.0.3-SNAPSHOT/klibfitbit-macosarm64-1.0.3-SNAPSHOT.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-macosarm64",
        "version": "1.0.3-SNAPSHOT"
      }
    }
  ]
}
