{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibfitbit",
    "module": "klibfitbit",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-metadata-1.0.3-SNAPSHOT.jar",
          "url": "klibfitbit-1.0.3-SNAPSHOT.jar",
          "size": 13911,
          "sha512": "5b356a384cf005a63a265ad4315937d1183d00aa317aff1f71992d0fc0c2f4775471c4960f4ce7855132ab268fd81b27d052cf2b0f9a86c16ebfa039a1d368c2",
          "sha256": "13f1a368779f6862f26b9081fe45ed41a201ef8778e973484a5df74cfbc2be2a",
          "sha1": "08761910e6974ab47f478bc32aa2c96f1b41197b",
          "md5": "df628a1a301911ba40cb088d6f03eb42"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibfitbit-kotlin-1.0.3-SNAPSHOT-sources.jar",
          "url": "klibfitbit-1.0.3-SNAPSHOT-sources.jar",
          "size": 17042,
          "sha512": "ea506490fc0fe8ab14f96cd70231241e0dfec4ed91bfe2801d4feeb63449dfe12d379aa5a976959f38d46219da20f81e490c9b797ff38eccb4107cafdeb8678e",
          "sha256": "55d0d2a47afbe367d2276b65cc444637be85ec1d1b928ae2d75aed330b865868",
          "sha1": "f6c4a281b2c23b0defe48cdadfb44d0a0f12e345",
          "md5": "4a6b027e148ad954320f73f7224cce4c"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibfitbit-jvm/1.0.3-SNAPSHOT/klibfitbit-jvm-1.0.3-SNAPSHOT.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-jvm",
        "version": "1.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibfitbit-jvm/1.0.3-SNAPSHOT/klibfitbit-jvm-1.0.3-SNAPSHOT.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-jvm",
        "version": "1.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibfitbit-jvm/1.0.3-SNAPSHOT/klibfitbit-jvm-1.0.3-SNAPSHOT.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-jvm",
        "version": "1.0.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibfitbit-macosarm64/1.0.3-SNAPSHOT/klibfitbit-macosarm64-1.0.3-SNAPSHOT.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-macosarm64",
        "version": "1.0.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibfitbit-macosarm64/1.0.3-SNAPSHOT/klibfitbit-macosarm64-1.0.3-SNAPSHOT.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-macosarm64",
        "version": "1.0.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibfitbit-macosarm64/1.0.3-SNAPSHOT/klibfitbit-macosarm64-1.0.3-SNAPSHOT.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-macosarm64",
        "version": "1.0.3-SNAPSHOT"
      }
    }
  ]
}
