{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibfitbit/1.0.2-SNAPSHOT/klibfitbit-1.0.2-SNAPSHOT.module",
    "group": "org.jraf.klibfitbit",
    "module": "klibfitbit",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.2-SNAPSHOT.jar",
          "url": "klibfitbit-jvm-1.0.2-SNAPSHOT.jar",
          "size": 66676,
          "sha512": "a42395bfa1975ef006ea61810ecda82e3c5dc278ddf48d2d615bf385f9c2b85a6afbb821b17dfb722aaf0b06a479ddec24f07caa98e935592f0a3fb40afbe207",
          "sha256": "c958190e1ed9968232bfa0079b950cb42d85fb1734f560f3c79ea2f778a7f520",
          "sha1": "aa7fcdca0ae390e1fa46676c933c0c130fec35f3",
          "md5": "c50a499a2c6c921b68d75d50187e29be"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.2-SNAPSHOT.jar",
          "url": "klibfitbit-jvm-1.0.2-SNAPSHOT.jar",
          "size": 66676,
          "sha512": "a42395bfa1975ef006ea61810ecda82e3c5dc278ddf48d2d615bf385f9c2b85a6afbb821b17dfb722aaf0b06a479ddec24f07caa98e935592f0a3fb40afbe207",
          "sha256": "c958190e1ed9968232bfa0079b950cb42d85fb1734f560f3c79ea2f778a7f520",
          "sha1": "aa7fcdca0ae390e1fa46676c933c0c130fec35f3",
          "md5": "c50a499a2c6c921b68d75d50187e29be"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.2-SNAPSHOT-sources.jar",
          "url": "klibfitbit-jvm-1.0.2-SNAPSHOT-sources.jar",
          "size": 15922,
          "sha512": "364f88209524896af79ac13993342f245d3f56048489a1ad0fc2353b3097ca6afcfae81226cf81e1a0b605dbdfc71998b32903d7665567e0150fff03e7319b40",
          "sha256": "dc1e65d1a5a2b93cda59ea04bb1eacb3554e9c23c1457909f001d1581e06349c",
          "sha1": "21eb91f51cdb856605bc339bc40943a0370873a3",
          "md5": "e162dcc2d1a0e2a9cde603d621d0428f"
        }
      ]
    }
  ]
}
