{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibfitbit/1.0.2-SNAPSHOT/klibfitbit-1.0.2-SNAPSHOT.module",
    "group": "org.jraf.klibfitbit",
    "module": "klibfitbit",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.2-SNAPSHOT.jar",
          "url": "klibfitbit-jvm-1.0.2-SNAPSHOT.jar",
          "size": 66662,
          "sha512": "3cd33e854d2bf68fbcabea7c15fa3857842f9eb9ec6426e96a6c26de1cad6cd689f048c716e184ca9579bbd4eb79a803a08e0935b430e99bd019afbb62a8fba4",
          "sha256": "71084fe359c3dd5bc23b1aa7ce43bfc2803a7bbd0028cd865376d7a610c47b0d",
          "sha1": "2c4b63db9388ae864659cc095937f8b546f01fd3",
          "md5": "948a7b29cfc3fe7e814b671918f0d13b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.2-SNAPSHOT.jar",
          "url": "klibfitbit-jvm-1.0.2-SNAPSHOT.jar",
          "size": 66662,
          "sha512": "3cd33e854d2bf68fbcabea7c15fa3857842f9eb9ec6426e96a6c26de1cad6cd689f048c716e184ca9579bbd4eb79a803a08e0935b430e99bd019afbb62a8fba4",
          "sha256": "71084fe359c3dd5bc23b1aa7ce43bfc2803a7bbd0028cd865376d7a610c47b0d",
          "sha1": "2c4b63db9388ae864659cc095937f8b546f01fd3",
          "md5": "948a7b29cfc3fe7e814b671918f0d13b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.2-SNAPSHOT-sources.jar",
          "url": "klibfitbit-jvm-1.0.2-SNAPSHOT-sources.jar",
          "size": 15860,
          "sha512": "de370fd2e2f0c59f9b48aff913a1b60cb0c64bd341a2340f2a97b54969ec84910a26f03bce965c37676085b7ea9f1ab4688dd10d8a1a8912da4cb8e8a7163064",
          "sha256": "20087ef1b1d86efa9bf1b4a297c828e92e3843ab415f9085d938212bee7c5c87",
          "sha1": "41bef8e793b16cb041eb76ac2b410553f0cf26fc",
          "md5": "851fb3842b57bf9432bc55912ce1d9b8"
        }
      ]
    }
  ]
}
