{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibfitbit/1.0.2-SNAPSHOT/klibfitbit-1.0.2-SNAPSHOT.module",
    "group": "org.jraf.klibfitbit",
    "module": "klibfitbit",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.2-SNAPSHOT.jar",
          "url": "klibfitbit-jvm-1.0.2-SNAPSHOT.jar",
          "size": 68280,
          "sha512": "07475a4d758e4654de06c3a94a7337aa415f8e974e1232e4702ce9720f176504bda12a77388e873aa9c1bce55c6849f740323299b157bf24a454e0aac964157c",
          "sha256": "c5c370b4c80c3e1eb1facf6ed96a2331fa654e5ebfb75bec4cc7866bfcf61177",
          "sha1": "68c83a210f42da2f0258bd7c40d3b3905cffa31e",
          "md5": "6bf9c972e65d594afd57bfcfd649edca"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.2-SNAPSHOT.jar",
          "url": "klibfitbit-jvm-1.0.2-SNAPSHOT.jar",
          "size": 68280,
          "sha512": "07475a4d758e4654de06c3a94a7337aa415f8e974e1232e4702ce9720f176504bda12a77388e873aa9c1bce55c6849f740323299b157bf24a454e0aac964157c",
          "sha256": "c5c370b4c80c3e1eb1facf6ed96a2331fa654e5ebfb75bec4cc7866bfcf61177",
          "sha1": "68c83a210f42da2f0258bd7c40d3b3905cffa31e",
          "md5": "6bf9c972e65d594afd57bfcfd649edca"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.2-SNAPSHOT-sources.jar",
          "url": "klibfitbit-jvm-1.0.2-SNAPSHOT-sources.jar",
          "size": 15929,
          "sha512": "dd038b1dccf684a117738882bbf582fa850a186c093bb4b8f8110106d2462efe7d2c96db4b2b4b66a206c2b1922af31d0cbb718edb37c97642ae56129d43f0c4",
          "sha256": "547c20cffe53189a8af76d7ccac1c90ffcbf8f3074dca3ab1187dbe103a0223e",
          "sha1": "fa0cbaa03898624de2b4de91be21ea1d4e8c7847",
          "md5": "644548c47d4cae4906419995a65840b6"
        }
      ]
    }
  ]
}
