{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibghealth",
    "module": "klibghealth",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibghealth-metadata-1.1.1-SNAPSHOT.jar",
          "url": "klibghealth-1.1.1-SNAPSHOT.jar",
          "size": 12403,
          "sha512": "392188b40c9d64b8b2fe5d6deac02fa75dc7bcbbf189a692f8088546974a4574e1240ee931b6ba06d125fe59d618d874f358b5adb59c0b68d12621ed7d4e356f",
          "sha256": "d9ace0977ab04cd24a2ae0a438f7529b5cd63f3aa9b9ac2dfadd36ee3cfe99a1",
          "sha1": "5f09cdeb670bd7fb86633e8f519603fa0555408d",
          "md5": "fa79eeaa4d7a38774066ca164c231ee5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibghealth-kotlin-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibghealth-1.1.1-SNAPSHOT-sources.jar",
          "size": 15467,
          "sha512": "4a46bb75d1653c7b5f1a8d899c20e5765201e4b290a4dda6840014fcf267b35709e9c4670cc5ad44b1965896f6ccfdf61a565ff3d8602e159084cadb0a3c348c",
          "sha256": "209bec88b57ef40cfd092c772771755af083404d65118fe091b5deb380e36cba",
          "sha1": "9b3726038872afac5a73e450e2ae814978eebc6d",
          "md5": "a26a1ab9275afdcfb63e44c032b55965"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibghealth-jvm/1.1.1-SNAPSHOT/klibghealth-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibghealth-jvm/1.1.1-SNAPSHOT/klibghealth-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibghealth-jvm/1.1.1-SNAPSHOT/klibghealth-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibghealth-macosarm64/1.1.1-SNAPSHOT/klibghealth-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibghealth-macosarm64/1.1.1-SNAPSHOT/klibghealth-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibghealth-macosarm64/1.1.1-SNAPSHOT/klibghealth-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    }
  ]
}
