{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibfitbit",
    "module": "klibfitbit",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-metadata-1.0.2.jar",
          "url": "klibfitbit-1.0.2.jar",
          "size": 13173,
          "sha512": "3eff6a070ded6212d2cd57de3354882c5fbce8b9808c3ec65d1d91d27c7b55621b486fe36710791c078a12f71e78002eb733655c022fb64f879e3efb087691e9",
          "sha256": "af97c1cbcf93c5e986801698e888e6ff669578a22ec8f26c32f9b10ed24ebdea",
          "sha1": "5274e73944cdf0c6e84ada9dfae2690280cdcb71",
          "md5": "8a057d160f9a5515a967379cc903d4f7"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibfitbit-kotlin-1.0.2-sources.jar",
          "url": "klibfitbit-1.0.2-sources.jar",
          "size": 15922,
          "sha512": "64091a3e75faef460096b70a5d89f956fe8d8c25633e7b183846fd7ba01a0858171c49614e389a88e47d33a0b8db4a3aeffac809cb39861f1de7f42b1d97286e",
          "sha256": "f1d760f69e5d8b75ccf4518469d9ab9479177d011ca082eb9b28450e5d4e691a",
          "sha1": "374e1a51097269d20035d5f167ae44a346b5955d",
          "md5": "6ca558f1942fb5e8310b7f20413761d4"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibfitbit-jvm/1.0.2/klibfitbit-jvm-1.0.2.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-jvm",
        "version": "1.0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibfitbit-jvm/1.0.2/klibfitbit-jvm-1.0.2.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-jvm",
        "version": "1.0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibfitbit-jvm/1.0.2/klibfitbit-jvm-1.0.2.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-jvm",
        "version": "1.0.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibfitbit-macosarm64/1.0.2/klibfitbit-macosarm64-1.0.2.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-macosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibfitbit-macosarm64/1.0.2/klibfitbit-macosarm64-1.0.2.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-macosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibfitbit-macosarm64/1.0.2/klibfitbit-macosarm64-1.0.2.module",
        "group": "org.jraf.klibfitbit",
        "module": "klibfitbit-macosarm64",
        "version": "1.0.2"
      }
    }
  ]
}
