{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibghealth",
    "module": "klibghealth",
    "version": "1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibghealth-metadata-1.1.0-SNAPSHOT.jar",
          "url": "klibghealth-1.1.0-SNAPSHOT.jar",
          "size": 12403,
          "sha512": "392188b40c9d64b8b2fe5d6deac02fa75dc7bcbbf189a692f8088546974a4574e1240ee931b6ba06d125fe59d618d874f358b5adb59c0b68d12621ed7d4e356f",
          "sha256": "d9ace0977ab04cd24a2ae0a438f7529b5cd63f3aa9b9ac2dfadd36ee3cfe99a1",
          "sha1": "5f09cdeb670bd7fb86633e8f519603fa0555408d",
          "md5": "fa79eeaa4d7a38774066ca164c231ee5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibghealth-kotlin-1.1.0-SNAPSHOT-sources.jar",
          "url": "klibghealth-1.1.0-SNAPSHOT-sources.jar",
          "size": 15468,
          "sha512": "b8059a8296990014c0b1701aaa26cc85ae036dfcff1a8775ef89cb95fafe0ec5800c1575223f5b45854e1542c76594922083ce2d90274df5622acebe821fc1b0",
          "sha256": "798933faa04a7b53e2927d411db394ccaae65a65c57683c196ad1146207ede53",
          "sha1": "5afe46d930876c5ae7a87583de3a9881a8f89b24",
          "md5": "17f4e94030e4cc83239703299743d258"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibghealth-jvm/1.1.0-SNAPSHOT/klibghealth-jvm-1.1.0-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-jvm",
        "version": "1.1.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibghealth-jvm/1.1.0-SNAPSHOT/klibghealth-jvm-1.1.0-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-jvm",
        "version": "1.1.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibghealth-jvm/1.1.0-SNAPSHOT/klibghealth-jvm-1.1.0-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-jvm",
        "version": "1.1.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibghealth-macosarm64/1.1.0-SNAPSHOT/klibghealth-macosarm64-1.1.0-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-macosarm64",
        "version": "1.1.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibghealth-macosarm64/1.1.0-SNAPSHOT/klibghealth-macosarm64-1.1.0-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-macosarm64",
        "version": "1.1.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibghealth-macosarm64/1.1.0-SNAPSHOT/klibghealth-macosarm64-1.1.0-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-macosarm64",
        "version": "1.1.0-SNAPSHOT"
      }
    }
  ]
}
