{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibfitbit/1.0.0-SNAPSHOT/klibfitbit-1.0.0-SNAPSHOT.module",
    "group": "org.jraf.klibfitbit",
    "module": "klibfitbit",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.0-SNAPSHOT.jar",
          "url": "klibfitbit-jvm-1.0.0-SNAPSHOT.jar",
          "size": 66433,
          "sha512": "587b66a3329b00e612d8ae5906e47876150c6e1d8dcca6a4418b08e3b478d37c5a0a9ce3c9a11a99405992e18c5eb154a404aea0a0c4e9e9b3f9a8fe3faed357",
          "sha256": "6bcea557692c916fb80e45ca00b4eefc50ad701f68101d0b929d8a54cf9d8edc",
          "sha1": "ab73532a5c9a2deae9621ff87fae9c5a70a5da2e",
          "md5": "a06cd340a767438e453004fb76c1d630"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.0-SNAPSHOT.jar",
          "url": "klibfitbit-jvm-1.0.0-SNAPSHOT.jar",
          "size": 66433,
          "sha512": "587b66a3329b00e612d8ae5906e47876150c6e1d8dcca6a4418b08e3b478d37c5a0a9ce3c9a11a99405992e18c5eb154a404aea0a0c4e9e9b3f9a8fe3faed357",
          "sha256": "6bcea557692c916fb80e45ca00b4eefc50ad701f68101d0b929d8a54cf9d8edc",
          "sha1": "ab73532a5c9a2deae9621ff87fae9c5a70a5da2e",
          "md5": "a06cd340a767438e453004fb76c1d630"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "klibfitbit-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 15813,
          "sha512": "b5bfbbf33c688203069fc061382842c8de26272a476d6487e5d59ca8679ec6c7c79e46501a5b55e27a782f175f7e6990c28e6705682b5ce35076c24c6c7103d8",
          "sha256": "244108931c71c2fbccda153ff8747025eb7d4a7fd78145058cd522b461a7bc57",
          "sha1": "00aa988e2f5baf14e23c200bb48f253d16359b94",
          "md5": "1544c9d6a67574a61ac445173beede4f"
        }
      ]
    }
  ]
}
