{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibghealth/1.1.1-SNAPSHOT/klibghealth-1.1.1-SNAPSHOT.module",
    "group": "org.jraf.klibghealth",
    "module": "klibghealth",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibghealth-jvm-1.1.1-SNAPSHOT.jar",
          "url": "klibghealth-jvm-1.1.1-SNAPSHOT.jar",
          "size": 125158,
          "sha512": "e92248233a98d4aa8e1560e486f9c4b4cd7dc7d8007fb2aeb8f9ba2a22314f3c90abd00fbf907f1313efc98372ea59d54aaeaec56c1339f40de7a06bf6d2aed4",
          "sha256": "759a94ad70f0aef89ac8dee3ff51b0adef7a89831069e9b6abf70aaab5f8fa34",
          "sha1": "15eeca2adcd5691dc261a5a8efe445d0f4bf6ae3",
          "md5": "e519baabe87b3b5543eee4517e944ad2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibghealth-jvm-1.1.1-SNAPSHOT.jar",
          "url": "klibghealth-jvm-1.1.1-SNAPSHOT.jar",
          "size": 125158,
          "sha512": "e92248233a98d4aa8e1560e486f9c4b4cd7dc7d8007fb2aeb8f9ba2a22314f3c90abd00fbf907f1313efc98372ea59d54aaeaec56c1339f40de7a06bf6d2aed4",
          "sha256": "759a94ad70f0aef89ac8dee3ff51b0adef7a89831069e9b6abf70aaab5f8fa34",
          "sha1": "15eeca2adcd5691dc261a5a8efe445d0f4bf6ae3",
          "md5": "e519baabe87b3b5543eee4517e944ad2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibghealth-jvm-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibghealth-jvm-1.1.1-SNAPSHOT-sources.jar",
          "size": 15467,
          "sha512": "4a46bb75d1653c7b5f1a8d899c20e5765201e4b290a4dda6840014fcf267b35709e9c4670cc5ad44b1965896f6ccfdf61a565ff3d8602e159084cadb0a3c348c",
          "sha256": "209bec88b57ef40cfd092c772771755af083404d65118fe091b5deb380e36cba",
          "sha1": "9b3726038872afac5a73e450e2ae814978eebc6d",
          "md5": "a26a1ab9275afdcfb63e44c032b55965"
        }
      ]
    }
  ]
}
