{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibfitbit/1.0.3-SNAPSHOT/klibfitbit-1.0.3-SNAPSHOT.module",
    "group": "org.jraf.klibfitbit",
    "module": "klibfitbit",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.3-SNAPSHOT.jar",
          "url": "klibfitbit-jvm-1.0.3-SNAPSHOT.jar",
          "size": 95754,
          "sha512": "ccc536906f71b0e860d163a0d1bd7edd7b1571b27315db97c637f5ee135501cf68ddb2b6290f4c3310d76c3eeb7de498dd56474860a8c8c117fb89987b87f1ab",
          "sha256": "66e63c4def9c5d3c1cf8f0431e0373d1931a269869059b209d48da2e4324fe7a",
          "sha1": "92af469b91e7de1ae9c31a884c4e36d192e5c9b8",
          "md5": "2ef86ba72380e90b9ae62ee35a0ab5cb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.3-SNAPSHOT.jar",
          "url": "klibfitbit-jvm-1.0.3-SNAPSHOT.jar",
          "size": 95754,
          "sha512": "ccc536906f71b0e860d163a0d1bd7edd7b1571b27315db97c637f5ee135501cf68ddb2b6290f4c3310d76c3eeb7de498dd56474860a8c8c117fb89987b87f1ab",
          "sha256": "66e63c4def9c5d3c1cf8f0431e0373d1931a269869059b209d48da2e4324fe7a",
          "sha1": "92af469b91e7de1ae9c31a884c4e36d192e5c9b8",
          "md5": "2ef86ba72380e90b9ae62ee35a0ab5cb"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.3-SNAPSHOT-sources.jar",
          "url": "klibfitbit-jvm-1.0.3-SNAPSHOT-sources.jar",
          "size": 17134,
          "sha512": "f772fa5595c9759c7e70363e5d851e1bce1ae8f84434bf24ed4e4a4c19b4151e717bc06f8d461fba72eab79eb9d9b4d328b3b0b489db35c9bc1c052431b2ce29",
          "sha256": "afe9e3dd5e694774d51cfc870ce3af69123098a7a34d16b10afc8206de0267a9",
          "sha1": "3af482ea89a034cd5cc1fa000cdda3d162eb2c6d",
          "md5": "bb7a32d68561b9d74a66f06517df25d6"
        }
      ]
    }
  ]
}
