{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibfitbit/1.0.3-SNAPSHOT/klibfitbit-1.0.3-SNAPSHOT.module",
    "group": "org.jraf.klibfitbit",
    "module": "klibfitbit",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.3-SNAPSHOT.jar",
          "url": "klibfitbit-jvm-1.0.3-SNAPSHOT.jar",
          "size": 96283,
          "sha512": "5d457448ae76b8c1e714402c155177090ec78bbc75f46fc406b5b699c28087f7f371041916ae8ba1b257b7f6a8b50b5e24b9ced4483612b6e2caae135971806e",
          "sha256": "c5d233f2c6aeb2edfdbaf2b93f1bb49a8f8c1c89f18743c7f98954a3e1bd1d63",
          "sha1": "187b3a5b22b679dadfb5504014f50c306e7c417b",
          "md5": "21749a7d37c04354eb93d0ab8d0f300e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.3-SNAPSHOT.jar",
          "url": "klibfitbit-jvm-1.0.3-SNAPSHOT.jar",
          "size": 96283,
          "sha512": "5d457448ae76b8c1e714402c155177090ec78bbc75f46fc406b5b699c28087f7f371041916ae8ba1b257b7f6a8b50b5e24b9ced4483612b6e2caae135971806e",
          "sha256": "c5d233f2c6aeb2edfdbaf2b93f1bb49a8f8c1c89f18743c7f98954a3e1bd1d63",
          "sha1": "187b3a5b22b679dadfb5504014f50c306e7c417b",
          "md5": "21749a7d37c04354eb93d0ab8d0f300e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.3-SNAPSHOT-sources.jar",
          "url": "klibfitbit-jvm-1.0.3-SNAPSHOT-sources.jar",
          "size": 17042,
          "sha512": "ea506490fc0fe8ab14f96cd70231241e0dfec4ed91bfe2801d4feeb63449dfe12d379aa5a976959f38d46219da20f81e490c9b797ff38eccb4107cafdeb8678e",
          "sha256": "55d0d2a47afbe367d2276b65cc444637be85ec1d1b928ae2d75aed330b865868",
          "sha1": "f6c4a281b2c23b0defe48cdadfb44d0a0f12e345",
          "md5": "4a6b027e148ad954320f73f7224cce4c"
        }
      ]
    }
  ]
}
