{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibghealth/1.1.0/klibghealth-1.1.0.module",
    "group": "org.jraf.klibghealth",
    "module": "klibghealth",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibghealth-jvm-1.1.0.jar",
          "url": "klibghealth-jvm-1.1.0.jar",
          "size": 125149,
          "sha512": "bb54c981673b7f9a811e02239d60055dd9583dfa9869b85ad91afab2715dc1a39d3a1453f67552126d0a76fcb74362c76f48881936c0cd9abcce7481ab35c3b9",
          "sha256": "f13be367fd0732e697a3205fce330314442f8cf2b9c656dccd2b20d58789d430",
          "sha1": "0505182b0dfe81c39d3d0d00b8505b205cfaaa6e",
          "md5": "044c576f2f9b07bb890192fbfba0ebf9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibghealth-jvm-1.1.0.jar",
          "url": "klibghealth-jvm-1.1.0.jar",
          "size": 125149,
          "sha512": "bb54c981673b7f9a811e02239d60055dd9583dfa9869b85ad91afab2715dc1a39d3a1453f67552126d0a76fcb74362c76f48881936c0cd9abcce7481ab35c3b9",
          "sha256": "f13be367fd0732e697a3205fce330314442f8cf2b9c656dccd2b20d58789d430",
          "sha1": "0505182b0dfe81c39d3d0d00b8505b205cfaaa6e",
          "md5": "044c576f2f9b07bb890192fbfba0ebf9"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibghealth-jvm-1.1.0-sources.jar",
          "url": "klibghealth-jvm-1.1.0-sources.jar",
          "size": 15460,
          "sha512": "7cf467ffc70945c8a6438a8e54435a77f3534c388b2f2db0763a27573be911ac59d68aea3bf1ac941ae4f75bb4616e3f2c71a4909a562cb2941d2a868a72fa6e",
          "sha256": "18151de7d5a439551a997fdb3383b8c346c8313577729e4e332391b9d8bf64a9",
          "sha1": "0ad130dd2ef7400229ab15be2281c1a4d7be5eb1",
          "md5": "245f1f036c1ba414ac9a8443dac891ca"
        }
      ]
    }
  ]
}
