{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibfitbit/1.0.1/klibfitbit-1.0.1.module",
    "group": "org.jraf.klibfitbit",
    "module": "klibfitbit",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.1.jar",
          "url": "klibfitbit-jvm-1.0.1.jar",
          "size": 66652,
          "sha512": "7b2d1d853802a6c7a632b87693f46cf487b488e146b95c67e366d5ef33f61105d0193587df691e1d5264eaf32e2381e5f3ff20f59933747c40c7823fa1ff51aa",
          "sha256": "887f86b39e5091524f69e6660180cc93c3573508f349e6fdbf49e012dd6a1da4",
          "sha1": "705667bc9d4f5ea27812176d771df2238e35f13e",
          "md5": "3c9938fca09c8f3cbd3b5ee07445e13e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.1.jar",
          "url": "klibfitbit-jvm-1.0.1.jar",
          "size": 66652,
          "sha512": "7b2d1d853802a6c7a632b87693f46cf487b488e146b95c67e366d5ef33f61105d0193587df691e1d5264eaf32e2381e5f3ff20f59933747c40c7823fa1ff51aa",
          "sha256": "887f86b39e5091524f69e6660180cc93c3573508f349e6fdbf49e012dd6a1da4",
          "sha1": "705667bc9d4f5ea27812176d771df2238e35f13e",
          "md5": "3c9938fca09c8f3cbd3b5ee07445e13e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibfitbit-jvm-1.0.1-sources.jar",
          "url": "klibfitbit-jvm-1.0.1-sources.jar",
          "size": 15853,
          "sha512": "c4b3d3e462deebb052d1a26b70b04413686bea1c879fb833e4274fe2e8c2dcfa76b576a669f0335767c15de47d8bed73a4860efe4dcc879762f9dcf5de67d006",
          "sha256": "7a2412bd66542b1d9131c855828c8a505e5102819252df1f6f86dc900209a091",
          "sha1": "d45cc2c4bb3ff566205adbdf0ae170b4e1310bdf",
          "md5": "896244fbadf6052a71b698efa81b04bc"
        }
      ]
    }
  ]
}
